// File generated by the Firebase CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX',
    authDomain: 'realgram-app.firebaseapp.com',
    projectId: 'realgram-app',
    storageBucket: 'realgram-app.appspot.com',
    messagingSenderId: '392827044546',
    appId: '1:392827044546:web:abcdefghijklmnopqrstuvwxyz',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX',
    appId: '1:392827044546:android:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '392827044546',
    projectId: 'realgram-app',
    storageBucket: 'realgram-app.appspot.com',
    databaseURL: 'https://realgram-app.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX',
    appId: '1:392827044546:ios:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '392827044546',
    projectId: 'realgram-app',
    storageBucket: 'realgram-app.appspot.com',
    databaseURL: 'https://realgram-app.firebaseio.com',
    iosClientId: 'realgram-app.apps.googleusercontent.com',
    iosBundleId: 'com.realgram.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX',
    appId: '1:392827044546:macos:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '392827044546',
    projectId: 'realgram-app',
    storageBucket: 'realgram-app.appspot.com',
    databaseURL: 'https://realgram-app.firebaseio.com',
    iosClientId: 'realgram-app.apps.googleusercontent.com',
    iosBundleId: 'com.realgram.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX',
    appId: '1:392827044546:windows:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '392827044546',
    projectId: 'realgram-app',
    storageBucket: 'realgram-app.appspot.com',
    databaseURL: 'https://realgram-app.firebaseio.com',
  );
}
